image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  before_script:
    - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - echo $IMAGE
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_TAG
    - docker build --build-arg "VERSION=${CI_COMMIT_TAG#v}" --pull -t $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG#v} .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG#v}
  only:
    - /^v\d+\.\d+\.\d+(-[\w-]+)?$/
  except:
    - branches
